import json
from typing import Any, Dict, List

import requests
import streamlit as st

st.set_page_config(page_title="Transcript to MCQ", layout="wide")


def _api_url(base_api_url: str, endpoint: str) -> str:
    return f"{base_api_url.rstrip('/')}/{endpoint.lstrip('/')}"


def _post_json(base_api_url: str, endpoint: str, payload: Dict[str, Any]) -> requests.Response:
    return requests.post(_api_url(base_api_url, endpoint), json=payload, timeout=300)


def _init_state() -> None:
    defaults = {
        "video_path": "",
        "transcript": "",
        "mcqs": [],
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


_init_state()

st.title("Transcript to MCQ Generator")
st.caption("Upload video -> transcribe -> generate MCQs from transcript")

with st.sidebar:
    st.header("Backend")
    base_api_url = st.text_input("API base URL", value="http://127.0.0.1:5000/api")
    if st.button("Check API"):
        try:
            r = requests.get(_api_url(base_api_url, "/get_transcript"), timeout=15)
            if r.ok:
                st.success("Backend is reachable")
            else:
                st.warning(f"Backend responded with status {r.status_code}")
        except Exception as exc:
            st.error(f"Cannot reach backend: {exc}")

st.subheader("1) Upload and Transcribe")
uploaded = st.file_uploader("Choose an MP4 video", type=["mp4"])

left, right = st.columns(2)

with left:
    if st.button("Upload Video", disabled=uploaded is None):
        try:
            files = {"video": (uploaded.name, uploaded.getvalue(), uploaded.type or "video/mp4")}
            response = requests.post(_api_url(base_api_url, "/upload"), files=files, timeout=300)
            response.raise_for_status()
            st.session_state.video_path = response.json().get("filepath", "")
            st.success("Video uploaded")
        except Exception as exc:
            st.error(f"Upload failed: {exc}")

with right:
    if st.button("Transcribe", disabled=not st.session_state.video_path):
        try:
            response = _post_json(
                base_api_url,
                "/transcribe",
                {"video_path": st.session_state.video_path},
            )
            response.raise_for_status()
            payload = response.json()
            st.session_state.transcript = payload.get("transcript", "")
            st.success(f"Transcription completed in {payload.get('time_taken', 'N/A')}s")
        except Exception as exc:
            st.error(f"Transcription failed: {exc}")

if st.session_state.video_path:
    st.text_input("Backend video path", value=st.session_state.video_path, disabled=True)

st.subheader("2) Transcript")
st.session_state.transcript = st.text_area(
    "Edit transcript before generating MCQs",
    value=st.session_state.transcript,
    height=220,
)

save_col, load_col = st.columns(2)
with save_col:
    if st.button("Save Transcript"):
        try:
            response = _post_json(
                base_api_url,
                "/edit_transcript",
                {"transcript": st.session_state.transcript},
            )
            response.raise_for_status()
            st.success("Transcript saved")
        except Exception as exc:
            st.error(f"Save failed: {exc}")

with load_col:
    if st.button("Load Saved Transcript"):
        try:
            response = requests.get(_api_url(base_api_url, "/get_transcript"), timeout=30)
            response.raise_for_status()
            st.session_state.transcript = response.json().get("transcript", "")
            st.success("Transcript loaded")
        except Exception as exc:
            st.error(f"Load failed: {exc}")

st.subheader("3) Generate MCQs")
controls_left, controls_right = st.columns(2)
with controls_left:
    num_questions = st.slider("Number of questions", min_value=3, max_value=20, value=8, step=1)
with controls_right:
    st.caption("MCQs and answers are generated by backend FLAN-T5 model")

if st.button("Generate MCQs", disabled=not st.session_state.transcript.strip()):
    try:
        response = _post_json(
            base_api_url,
            "/generate_mcqs",
            {
                "transcript": st.session_state.transcript,
                "num_questions": int(num_questions),
            },
        )
        response.raise_for_status()
        payload = response.json()
        st.session_state.mcqs = payload.get("mcqs", [])

        if st.session_state.mcqs:
            st.success(f"Generated {len(st.session_state.mcqs)} MCQs")
        else:
            st.warning("No MCQs were generated. Try a longer transcript.")
    except Exception as exc:
        st.error(f"MCQ generation failed: {exc}")

if st.session_state.mcqs:
    show_answers = st.checkbox("Show answers", value=False)
    for item in st.session_state.mcqs:
        st.markdown(f"**Q{item['question_no']}. {item['question']}**")
        for idx, opt in enumerate(item["options"]):
            label = chr(65 + idx)
            st.write(f"{label}. {opt}")
        if show_answers:
            st.info(f"Answer: {item['answer']}")
        st.divider()

    export_payload = json.dumps(st.session_state.mcqs, indent=2)
    st.download_button(
        "Download MCQs as JSON",
        data=export_payload,
        file_name="mcqs.json",
        mime="application/json",
    )
